config/urls.py
from django.conf                                            import settings
from django.conf.urls.static                                import static
from django.contrib                                         import admin
from django.urls                                            import path, include


urlpatterns = [

    path('',                        include('weather.apps.urls')),

]

if settings.DEBUG:

    import debug_toolbar

    urlpatterns = [

        path('admin/',                              admin.site.urls),
        path('__debug__/',                          include(debug_toolbar.urls)),

    ] + urlpatterns

    urlpatterns = urlpatterns + static(
                            settings.STATIC_URL, document_root=settings.STATIC_ROOT
                        )
    urlpatterns = urlpatterns + static(
                            settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
                        )

weather/apps/api/climate/urls.py
from django.urls                                            import path

from weather.apps.api.climate.viewsets                      import weather_home, city_weather
from weather.apps.api.climate.chart                         import WeatherChartView


app_name = 'city_weather'

urlpatterns = [

    path('',                    weather_home,                   name = 'api_home'),
    path('chart/',              WeatherChartView.as_view(),     name='chart'),
    path('list/',               city_weather,                   name = 'list'),

]

weather/apps/api/urls.py
from django.urls                                        import path, include


urlpatterns = [

    path('climate/',                    include('weather.apps.api.climate.urls')),

]

weather/apps/urls.py
from django.urls                                        import path, include


urlpatterns = [

    path('',                    include('weather.apps.web.urls')),
    path('api/',                include('weather.apps.api.urls')),

]

weather/apps/web/climate/urls.py
from django.urls                                        import path

from weather.apps.web.climate.views                     import ClimateListView
from weather.apps.web.climate.weather                   import WeathersListView
from weather.apps.web.climate.chart                     import WeatherChartView


app_name = 'climate'

urlpatterns = [

    path('',                ClimateListView.as_view(),              name='home'),
    path('chart/',          WeatherChartView.as_view(),             name='chart'),
    path('list/',           WeathersListView.as_view(),             name='weather_list'),

]

weather/apps/web/urls.py
from django.urls                                        import path, include


urlpatterns = [

    path('',                    include('weather.apps.web.climate.urls')),

]

weather/apps/web/climate/models.py
from django.db                                          import models
from django_countries.fields                            import CountryField

from core.model_mixins                                  import AuditFields


# Create your models here.
class Climate(AuditFields):

    city            = models.CharField('CITY',      max_length=255, blank=True, null=True)

    country         = CountryField('COUNTRY',                       blank=True, null=True)

    lat             = models.FloatField('LATITUDE',                 default=0.00)
    lng             = models.FloatField('LONGITUDE',                default=0.00)

    weather_time    = models.DateTimeField('WEATHER TIME',          blank=True, null=True)
    period_start    = models.DateTimeField('START PERIOD',          blank=True, null=True)
    period_end      = models.DateTimeField('END PERIOD',            blank=True, null=True)

    min_temp        = models.FloatField('MIN. TEMP',                default=0.00)
    max_temp        = models.FloatField('MAX. TEMP',                default=0.00)
    avg_temp        = models.FloatField('AVERAGE. TEMP',            default=0.00)
    med_temp        = models.FloatField('MEDIAN. TEMP',             default=0.00)

    humidity        = models.CharField('HUMIDITY',      max_length=200, blank=True, null=True)
    description     = models.CharField('DESCRIPTION',   max_length=200, blank=True, null=True)
    sunrise         = models.CharField('SUNRISE',       max_length=200, blank=True, null=True)
    sunset          = models.CharField('SUNSET',        max_length=200, blank=True, null=True)
    icon            = models.CharField('WEATHER ICON',  max_length=200, blank=True, null=True)

    class Meta:
        app_label   = 'climate'
        db_table    = 'btk_climates'

    def __str__(self):
        return self.city

weather/apps/web/climate/forms.py
from django.forms                                   import forms

from crispy_forms.layout                            import Layout
from crispy_forms.bootstrap                         import StrictButton
from crispy_forms.helper                            import FormHelper
from crispy_forms.layout                            import Layout, Fieldset, ButtonHolder, Submit


class ClimateForm(forms.Form):

    class Meta:
        fields = ['city', 'period_start', 'period_end']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_class = 'form-inline'
        self.helper.layout = Layout(
            Fieldset(
                'city',
                'period_start',
                'period_end',
            ),
            ButtonHolder(
                Submit('submit', 'Submit', css_class='button white')
            )
        )

weather/apps/web/climate/views.py
import requests
from datetime                                           import datetime

from django.contrib                                     import messages
from django.shortcuts                                   import render
from django.views.generic                               import View

from weather.apps.web.climate.forms                     import ClimateForm
from weather.apps.web.climate.lib.input                 import input_get_input


# Create your views here.
class ClimateListView(View):
    template_name = 'apps/climate/index.html'

    def get(self, request, **kwargs):

        form = ClimateForm

        context = {}

        if request.GET:

            i = input_get_input(request)

            hostname = request.get_host()

            btk_api = f'http://{hostname}/api/climate/list/'

            city_req        = i['city']
            period_start    = i['period_start']
            period_end      = i['period_end']

            full_url = f"{btk_api}?city={city_req}&period_start={period_start}&period_end={period_end}"

            res         = requests.get(full_url)
            res_json    = res.json()

            if 'list' in res_json:
                if len(res_json['list']) > 0:
                    time = datetime.strptime(res_json['list'][0]['list_txt'], "%Y-%m-%dT%H:%M:%S")

                    weather = {
                        'city'          : res_json['city'],
                        'temperature'   : res_json['list'][0]['avg_temp'],
                        'description'   : res_json['list'][0]['description'],
                        'humidity'      : res_json['list'][0]['humidity'],
                        'icon'          : res_json['list'][0]['icon'],
                        'time'          : time,
                    }

                    context['weather'] = weather

                else:

                    messages.warning(request, "No data to report. Please, note that reports are at 3 hr intervals.")


            context['results'] = res_json

        context['form'] = form

        return render(request, self.template_name, context)

weather/templates/apps/climate/chart.html
{% extends 'base.html' %}

{% block content %}
    
    <div id="container" style="width: 75%;">
        <canvas id="min-weather-chart" data-url="{% url 'climate:chart' %}"></canvas>
    </div>
    <div id="container" style="width: 75%;">
        <canvas id="max-weather-chart" data-url="{% url 'climate:chart' %}"></canvas>
    </div>
    <div id="container" style="width: 75%;">
        <canvas id="avg-weather-chart" data-url="{% url 'climate:chart' %}"></canvas>
    </div>
    <div id="container" style="width: 75%;">
        <canvas id="hum-weather-chart" data-url="{% url 'climate:chart' %}"></canvas>
    </div>

    {% include 'includes/script.html' %}

    <script>

        var data_url    = '/api/climate/chart/';

        var min_temp_data   = [];
        var max_temp_data   = [];
        var avg_temp_data   = [];
        var humidity_data   = [];
        var min_temp_labels = [];
        var max_temp_labels = [];
        var avg_temp_labels = [];
        var humidity_labels = [];
        $.ajax({
            method  : "GET",
            url     : data_url,

            success : function (res_data) {

                min_temp_data   = res_data.min_temp_data
                max_temp_data   = res_data.max_temp_data
                avg_temp_data   = res_data.avg_temp_data
                humidity_data   = res_data.humidity_data

                min_temp_labels = res_data.min_temp_labels
                max_temp_labels = res_data.max_temp_labels
                avg_temp_labels = res_data.avg_temp_labels
                humidity_labels = res_data.humidity_labels

                plotChart()

            },
            error : function (error_data) {

                console.log("Error");
                console.log(error_data)

            }
        });

        function plotChart() {

            var minCtx = document.getElementById('min-weather-chart');
            var maxCtx = document.getElementById('max-weather-chart');
            var avgCtx = document.getElementById('avg-weather-chart');
            var humCtx = document.getElementById('hum-weather-chart');

            var min_tempChart = new Chart(minCtx, {
                type: 'bar',
                data: {
                    labels: min_temp_labels,
                    datasets: [{
                        label: 'Average Min Temp Chart by City',
                        data: min_temp_data,
                        backgroundColor: [
                            'rgba(255, 99, 132, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(255, 206, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(255, 159, 64, 0.2)',

                            'rgba(255, 206, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(255, 159, 64, 0.2)'
                        ],
                        borderColor: [
                            'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(255, 159, 64, 1)',

                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(255, 159, 64, 1)'
                        ],
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true,
                            },
                            scaleLabel: {
                                display: true,
                                labelString: 'Average min Temp.'
                            }
                        }],
                        xAxes: [{
                            scaleLabel: {
                                display: true,
                                labelString: 'Cities'
                            }
                        }],
                    }
                }
            });
            var max_tempChart = new Chart(maxCtx, {
                type: 'line',
                data: {
                    labels: max_temp_labels,
                    datasets: [{
                        label: 'Average Max Temp Chart by City',
                        data: max_temp_data,
                        backgroundColor: [
                            'rgba(255, 99, 132, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(255, 206, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(255, 159, 64, 0.2)',

                            'rgba(255, 206, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(255, 159, 64, 0.2)'
                        ],
                        borderColor: [
                            'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(255, 159, 64, 1)',

                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(255, 159, 64, 1)'
                        ],
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true,
                            },
                            scaleLabel: {
                                display: true,
                                labelString: 'Average Max Temp.'
                            }
                        }],
                        xAxes: [{
                            scaleLabel: {
                                display: true,
                                labelString: 'Cities'
                            }
                        }],
                    }
                }
            });
            var avg_tempChart = new Chart(avgCtx, {
                type: 'radar',
                data: {
                    labels: avg_temp_labels,
                    datasets: [{
                        label: 'Weather Average Temp Chart by City',
                        data: avg_temp_data,
                        backgroundColor: [
                            'rgba(255, 99, 132, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(255, 206, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(255, 159, 64, 0.2)',

                            'rgba(255, 206, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(255, 159, 64, 0.2)'
                        ],
                        borderColor: [
                            'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(255, 159, 64, 1)',

                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(255, 159, 64, 1)'
                        ],
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true,
                            },
                            scaleLabel: {
                                display: true,
                                labelString: 'Average Temp.'
                            }
                        }],
                        xAxes: [{
                            scaleLabel: {
                                display: true,
                                labelString: 'Cities'
                            }
                        }],
                    }
                }
            });
            var humChart = new Chart(humCtx, {
                type: 'polarArea',
                data: {
                    labels: humidity_labels,
                    datasets: [{
                        label: 'Weather Humidity Chart by City',
                        data: humidity_data,
                        backgroundColor: [
                            'rgba(255, 99, 132, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(255, 206, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(255, 159, 64, 0.2)',

                            'rgba(255, 206, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(255, 159, 64, 0.2)'
                        ],
                        borderColor: [
                            'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(255, 159, 64, 1)',

                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(255, 159, 64, 1)'
                        ],
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true,
                            },
                            scaleLabel: {
                                display: true,
                                labelString: 'Average Humidity.'
                            }
                        }],
                        xAxes: [{
                            scaleLabel: {
                                display: true,
                                labelString: 'Cities'
                            }
                        }],
                    }
                }
            });
        }


    </script>

{% endblock %}

weather/templates/apps/climate/index.html
{% extends '../../base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block section %}
    <section class="hero is-primary" style="background-color: #00e7eb; padding: 5px">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    How is the weather out there?
                </h1>
                <div align="right">
                    <h5>Accepted time formats: 10:00 AM, or 07:30 PM</h5>
                </div>
            </div>
        </div>
    </section>
{% endblock section %}

{% block content %}

<div class="card text-center">

    <div class="row">
        <div class="col">
            <div class="card card-body">

                {% if not weather %}
                    {{ results.bad_request }}
                {% endif %}

                <article class="media" style="padding: 5px">
                    <div class="media-left">
                        <figure class="image is-50x50">
                            {% if weather.icon %}
                                <img src="http://openweathermap.org/img/w/{{ weather.icon }}.png" alt="Image">
                            {% endif %}
                        </figure>
                    </div>
                    <div class="media-content">
                        <div class="content">
                            <p>
                                <span class="title">
                                    <strong>{{ weather.city }}</strong>
                                </span>
                                <br>
                                <span class="subtitle">
                                    {% if weather.temperature %}
                                        {{ weather.temperature }}° C
                                    {% endif %}
                                </span>
                                <br>{% if weather.humidity %}
                                    Humidity : {{ weather.humidity }}
                                {% endif %}
                                <br>{{ weather.description }}<br>
                                {% if weather.time %}For <strong>{{ weather.time|date:"d-m-Y H:i" }}</strong>{% endif %}
                            </p>
                        </div>
                    </div>
                </article>
            </div>
        </div>
    </div>

    <div class="card-body">

        <br>
        <form action="" method="GET">
{#            {% csrf_token %}#}

            <input type="text" id="city" name="city" placeholder="Enter City Name" required>
            <label>Period Start</label>
            <input type="time" id="period_start" name="period_start" required>
            <label>Period End</label>
            <input type="time" id="period_end" name="period_end" required>

            <div style="padding: 10px; margin-top: 10px">
                <button class="btn btn-default" type="submit" style="background-color: #00e7eb">Check</button>
            </div>
        </form>

        <br>
        <h5 class="card-title">Please enter the city name and time period (defaulted to today)</h5>
    </div>
</div>

{% endblock content %}

weather/templates/apps/climate/weather_chart.html
{% extends 'base.html' %}

{% block content %}
    
    <div id="container" style="width: 75%;">
        <canvas id="weather-chart" data-url="{% url 'climate:chart' %}"></canvas>

        <div align="right">
            <button class="btn btn-primary">Submit</button>
        </div>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <script>
        
        $(function () {
        
            var $weatherChart = $("#weather-chart");
            
            $.ajax({
                url: $weatherChart.data("url"),
                success: function (data) {
                
                var ctx = $weatherChart[0].getContext("2d");
                
                new Chart(ctx, {
                    type: 'bar',
                    data: {
                        labels: data.labels,
                        datasets: [{
                            label: 'Weather',
                            backgroundColor: 'blue',
                            data: data.data
                        }]          
                    },
                    options: {
                        responsive: true,
                        legend: {
                            position: 'top',
                        },
                        title: {
                            display: true,
                            text: 'Weather Bar Chart'
                        }
                    }
                });
                
                }
            });
        
        });
    
    </script>

{% endblock %}

weather/templates/apps/climate/weather_list.html
{% extends '../../base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block section %}
{% endblock section %}

{% block content %}

    <div class="card text-center">

        <div class="row">
            <div class="col">
                <div class="card card-body">

                <br><br>

                    <table class="table table-hover">
                        <thead  style="background-color: darkturquoise">
                            <th>City</th>
                            <th>Min Temp</th>
                            <th>Max Temp</th>
                            <th>Avg Temp</th>
                            <th>Humidity</th>
                            <th>Time Period</th>
                        </thead>

                        {% for weather in weathers %}
                        <tbody>
                            <tr>
                                <td>
                                    {% ifchanged weather.city %}
                                        {{ weather.city }}
                                    {% endifchanged %}
                                </td>
                                <td>{{ weather.min_temp }}° C</td>
                                <td>{{ weather.max_temp }}° C</td>
                                <td>{{ weather.avg_temp }}° C</td>
                                <td>{{ weather.humidity }}</td>
                                <td>
                                    {% ifchanged weather.period_start %}
                                        {{ weather.period_start|date:"d-m-Y H:i" }} - {{ weather.period_end|date:"d-m-Y H:i" }}
                                    {% endifchanged %}
                                </td>
                            </tr>
                        </tbody>
                        {% endfor %}

                    </table>

                </div>
            </div>
        </div>
    </div>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script>
    var data_url = 'http://localhost:9800/api/climate/chart/';

    $.ajax({
        method: "GET",
        url: data_url,

        success: function (data) {
            console.log("SUCCESS");
            // console.log(data)

        },
    });
</script>

{% endblock content %}

weather/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta charset="UTF-8">
        <title>BTK - Weather</title>
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" >
    </head>
    <body style="background-color: #F5F5F5">

    {% include 'includes/navbar.html' %}

    {% block section %}
    {% endblock section %}

    {% if messages %}
        {% for message in messages %}

        <div class="alert alert-info border-0 alert-dismissible" id="alert-info">
            <button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>{{ message }}.
        </div>

        {% endfor %}
    {% endif %}

    {% block content %}
    {% endblock content %}

    </body>
</html>

weather/templates/includes/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">BTK Weather API &nbsp;| &nbsp;&nbsp;</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
<!--            <li class="nav-item active">-->
<!--                <a class="nav-link" href="/">&nbsp; Home &nbsp; <span class="sr-only">(current)</span></a>-->
<!--            </li>-->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'climate:weather_list' %}?{{ request.GET.urlencode }}">&nbsp; Weather List </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'climate:chart' %}?{{ request.GET.urlencode }}">&nbsp; Chart </a>
            </li>
        </ul>
    </div>
</nav>

weather/templates/includes/script.html
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>